"""
Simple interaction log reader
Reads logs generated by baseline.py
"""
import json
from typing import List, Dict, Any
from pathlib import Path


class InteractionLogReader:
    """Reads user interaction logs from JSONL files"""
    
    def __init__(self, log_path: str = "interaction_logs.jsonl"):
        self.log_path = Path(log_path)
        
    def load_interactions(self, limit: int = None) -> List[Dict]:
        """Load interaction logs from file"""
        if not self.log_path.exists():
            alt_paths = [
                Path("data/raw/interaction_logs.jsonl"),
                Path("interaction_logs.jsonl")
            ]
            for alt in alt_paths:
                if alt.exists():
                    self.log_path = alt
                    break
            else:
                return []
        
        interactions = []
        with open(self.log_path, 'r') as f:
            for line in f:
                if line.strip():
                    raw = json.loads(line)
                    interaction = self._normalize_interaction(raw)
                    interactions.append(interaction)
                    if limit and len(interactions) >= limit:
                        break
        
        return interactions
    
    def _normalize_interaction(self, raw: Dict) -> Dict:
        """Normalize interaction to standard format"""
        # If already in extended format
        if 'actions' in raw and isinstance(raw['actions'], list):
            if raw['actions'] and isinstance(raw['actions'][0], dict):
                return raw
        
        # Convert from baseline.py format
        ranked_ids = raw.get('ranked_article_ids', [])
        raw_actions = raw.get('actions', [])
        
        parsed_actions = []
        for idx, article_id in enumerate(ranked_ids):
            article_actions = raw_actions[idx] if idx < len(raw_actions) else []
            
            action_dict = {
                'article_id': article_id,
                'position': idx,
                'clicked': False,
                'dwell_time_secs': 0.0,
                'liked': False,
                'shared': False,
                'bookmarked': False,
                'skipped': len(article_actions) == 0
            }
            
            for action in article_actions:
                if action == "Click":
                    action_dict['clicked'] = True
                elif isinstance(action, dict) and "Dwell" in action:
                    dwell = action["Dwell"]
                    action_dict['dwell_time_secs'] = dwell['secs'] + dwell['nanos'] / 1e9
                elif action == "Like":
                    action_dict['liked'] = True
                elif action == "Share":
                    action_dict['shared'] = True
                elif action == "Bookmark":
                    action_dict['bookmarked'] = True
            
            parsed_actions.append(action_dict)
        
        return {
            'query_id': raw.get('query_id'),
            'user_id': raw.get('user_id'),
            'query_text': raw.get('query_text'),
            'actions': parsed_actions
        }
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get summary statistics from logs"""
        interactions = self.load_interactions()
        
        if not interactions:
            return {'total_queries': 0}
        
        total_queries = len(interactions)
        total_clicks = sum(
            sum(1 for a in i['actions'] if a['clicked'])
            for i in interactions
        )
        total_results = sum(len(i['actions']) for i in interactions)
        
        return {
            'total_queries': total_queries,
            'total_clicks': total_clicks,
            'total_results': total_results,
            'unique_users': len(set(i['user_id'] for i in interactions)),
            'avg_ctr': total_clicks / total_results if total_results > 0 else 0
        }


# Alias for backward compatibility
InteractionLogger = InteractionLogReader
